[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableXsrfProtection = false
enableCORS = false
maxUploadSize = 50

[browser]
gatherUsageStats = false
